### ISSUE TITLE
Cloned clips behave weird when notes are deleted

### ISSUE THREAD

**Issue by Paul-Andre** [rezoner/chirp#2]
When I clone a clip a couple of times, and then edit a cloned clip, there is some weird behaviour.

The most obvious case is that when I try to delete a note, that note gets deleted in all the clips, but not in the one you were editing, but it instead deletes some random note. Sometimes, when I delete a note, lots of random notes get deleted.

**Comment by rezoner** [comment]
Hopefully it is fixed now
