### ISSUE TITLE
Provide alternative to middle mouse button

### ISSUE THREAD

**Issue by joanrieu** [rezoner/chirp#8]
A usable middle mouse button is not always available and since it has to be used to move things around, a modifier key like shift or ctrl (combined with the left mouse button) would be a nice thing to have.

**Comment by rezoner** [comment]
Try shift + mouse wheel instead. Does it helped?

**Comment by joanrieu** [comment]
Right, I don't know how I missed that.
The direction is reversed compared to other software though.

**Comment by rezoner** [comment]
Ok, reversed.
